name: Clouds-Lab3
version: 0.1.0.0
github: "petals-of-white/Clouds-Lab3"
license: MIT
author: "Maksym Syvash"
maintainer: "maksym_syvash@outlook.com"
copyright: "2024 Maksym Syvash"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/petals-of-white/Clouds-Lab3#readme>

language: GHC2021
dependencies:
  - base >= 4.7 && < 5
  - text
  - filepath
  - containers
  - scotty
  - uuid
  - aeson

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  Clouds-Lab3-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Clouds-Lab3
      - scotty
      - transformers
      - aeson
      - unliftio-core
      - http-types
      - hasql
      - hasql-th
      - contravariant-extras
      - bytestring
      - mtl
      - co-log
tests:
  Clouds-Lab3-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Clouds-Lab3
