name: Deploying a Haskell app to Azure Web app Container

on: 
    push:
        branches : ["scotty", "main"]
    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4

    - name: "Log in using docker"
      uses: azure/docker-login@v2
      with:
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: "Build and push docker image"
      run: |
        docker build --cache-from=${{ vars.DOCKER_IMAGE_NAME }}:latest . -t ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }} 

  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: "Deploy the container to Azure Web app" 
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ vars.DOCKER_IMAGE_NAME }}:${{ github.sha }}'